// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: android_signer.proto

package rust.nostr.android.signer.proxy.protobuf;

public final class AndroidSignerProxyProto {
  private AndroidSignerProxyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IsExternalSignerInstalledRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:android_signer.IsExternalSignerInstalledRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code android_signer.IsExternalSignerInstalledRequest}
   */
  public static final class IsExternalSignerInstalledRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:android_signer.IsExternalSignerInstalledRequest)
      IsExternalSignerInstalledRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IsExternalSignerInstalledRequest.newBuilder() to construct.
    private IsExternalSignerInstalledRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IsExternalSignerInstalledRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IsExternalSignerInstalledRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.internal_static_android_signer_IsExternalSignerInstalledRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.internal_static_android_signer_IsExternalSignerInstalledRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest.class, rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest)) {
        return super.equals(obj);
      }
      rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest other = (rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code android_signer.IsExternalSignerInstalledRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:android_signer.IsExternalSignerInstalledRequest)
        rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.internal_static_android_signer_IsExternalSignerInstalledRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.internal_static_android_signer_IsExternalSignerInstalledRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest.class, rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest.Builder.class);
      }

      // Construct using rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.internal_static_android_signer_IsExternalSignerInstalledRequest_descriptor;
      }

      @java.lang.Override
      public rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest getDefaultInstanceForType() {
        return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest.getDefaultInstance();
      }

      @java.lang.Override
      public rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest build() {
        rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest buildPartial() {
        rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest result = new rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest) {
          return mergeFrom((rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest other) {
        if (other == rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:android_signer.IsExternalSignerInstalledRequest)
    }

    // @@protoc_insertion_point(class_scope:android_signer.IsExternalSignerInstalledRequest)
    private static final rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest();
    }

    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IsExternalSignerInstalledRequest>
        PARSER = new com.google.protobuf.AbstractParser<IsExternalSignerInstalledRequest>() {
      @java.lang.Override
      public IsExternalSignerInstalledRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IsExternalSignerInstalledRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IsExternalSignerInstalledRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IsExternalSignerInstalledReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:android_signer.IsExternalSignerInstalledReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool installed = 1;</code>
     * @return The installed.
     */
    boolean getInstalled();
  }
  /**
   * Protobuf type {@code android_signer.IsExternalSignerInstalledReply}
   */
  public static final class IsExternalSignerInstalledReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:android_signer.IsExternalSignerInstalledReply)
      IsExternalSignerInstalledReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IsExternalSignerInstalledReply.newBuilder() to construct.
    private IsExternalSignerInstalledReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IsExternalSignerInstalledReply() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IsExternalSignerInstalledReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.internal_static_android_signer_IsExternalSignerInstalledReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.internal_static_android_signer_IsExternalSignerInstalledReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply.class, rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply.Builder.class);
    }

    public static final int INSTALLED_FIELD_NUMBER = 1;
    private boolean installed_ = false;
    /**
     * <code>bool installed = 1;</code>
     * @return The installed.
     */
    @java.lang.Override
    public boolean getInstalled() {
      return installed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (installed_ != false) {
        output.writeBool(1, installed_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (installed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, installed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply)) {
        return super.equals(obj);
      }
      rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply other = (rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply) obj;

      if (getInstalled()
          != other.getInstalled()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INSTALLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getInstalled());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code android_signer.IsExternalSignerInstalledReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:android_signer.IsExternalSignerInstalledReply)
        rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.internal_static_android_signer_IsExternalSignerInstalledReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.internal_static_android_signer_IsExternalSignerInstalledReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply.class, rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply.Builder.class);
      }

      // Construct using rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        installed_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.internal_static_android_signer_IsExternalSignerInstalledReply_descriptor;
      }

      @java.lang.Override
      public rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply getDefaultInstanceForType() {
        return rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply.getDefaultInstance();
      }

      @java.lang.Override
      public rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply build() {
        rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply buildPartial() {
        rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply result = new rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.installed_ = installed_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply) {
          return mergeFrom((rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply other) {
        if (other == rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply.getDefaultInstance()) return this;
        if (other.getInstalled() != false) {
          setInstalled(other.getInstalled());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                installed_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean installed_ ;
      /**
       * <code>bool installed = 1;</code>
       * @return The installed.
       */
      @java.lang.Override
      public boolean getInstalled() {
        return installed_;
      }
      /**
       * <code>bool installed = 1;</code>
       * @param value The installed to set.
       * @return This builder for chaining.
       */
      public Builder setInstalled(boolean value) {
        
        installed_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool installed = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstalled() {
        bitField0_ = (bitField0_ & ~0x00000001);
        installed_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:android_signer.IsExternalSignerInstalledReply)
    }

    // @@protoc_insertion_point(class_scope:android_signer.IsExternalSignerInstalledReply)
    private static final rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply();
    }

    public static rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IsExternalSignerInstalledReply>
        PARSER = new com.google.protobuf.AbstractParser<IsExternalSignerInstalledReply>() {
      @java.lang.Override
      public IsExternalSignerInstalledReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IsExternalSignerInstalledReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IsExternalSignerInstalledReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rust.nostr.android.signer.proxy.protobuf.AndroidSignerProxyProto.IsExternalSignerInstalledReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_signer_IsExternalSignerInstalledRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_signer_IsExternalSignerInstalledRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_signer_IsExternalSignerInstalledReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_signer_IsExternalSignerInstalledReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024android_signer.proto\022\016android_signer\"\"" +
      "\n IsExternalSignerInstalledRequest\"3\n\036Is" +
      "ExternalSignerInstalledReply\022\021\n\tinstalle" +
      "d\030\001 \001(\0102\220\001\n\rAndroidSigner\022\177\n\031IsExternalS" +
      "ignerInstalled\0220.android_signer.IsExtern" +
      "alSignerInstalledRequest\032..android_signe" +
      "r.IsExternalSignerInstalledReply\"\000BC\n(ru" +
      "st.nostr.android.signer.proxy.protobufB\027" +
      "AndroidSignerProxyProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_android_signer_IsExternalSignerInstalledRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_android_signer_IsExternalSignerInstalledRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_signer_IsExternalSignerInstalledRequest_descriptor,
        new java.lang.String[] { });
    internal_static_android_signer_IsExternalSignerInstalledReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_android_signer_IsExternalSignerInstalledReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_signer_IsExternalSignerInstalledReply_descriptor,
        new java.lang.String[] { "Installed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
