name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        run: rustup install nightly

      - name: Add rustfmt for nightly
        run: rustup component add rustfmt --toolchain nightly

      - name: Check
        working-directory: signer
        run: cargo +nightly fmt --all --check -- --config format_code_in_doc_comments=true

  check:
    name: Check crates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - nostr-android-signer-proto
          - nostr-android-signer-proxy
          - nostr-android-signer
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.8
      with:
        key: ${{ matrix.crate }}

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Check
      run: cargo check -p ${{ matrix.crate }}

    - name: Clippy
      run: cargo clippy -p ${{ matrix.crate }} -- -D warnings

    - name: Test
      run: cargo test -p ${{ matrix.crate }}
