name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        run: rustup install nightly

      - name: Add rustfmt for nightly
        run: rustup component add rustfmt --toolchain nightly

      - name: Check
        working-directory: signer
        run: cargo +nightly fmt --all --check -- --config format_code_in_doc_comments=true

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.8
      with:
        workspaces: signer

    - name: Install protoc
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y protobuf-compiler libprotobuf-dev

    - name: Check
      working-directory: signer
      run: cargo check

    - name: Clippy
      working-directory: signer
      run: cargo clippy -- -D warnings

    - name: Test
      working-directory: signer
      run: cargo test
